"""Per-transition executability probes for HLPSL models (follow-up Part C2).

A SAFE verdict means little if the protocol cannot run: a goal on a transition that never fires holds
trivially. For each transition of each role this writes a probe copy of the model in which that
transition's right-hand side also sends a fresh marker in clear, declared
secret(marker, probe_<role><n>, {owner}). A secrecy attack on probe_<role><n> proves that transition
can execute; SAFE on it means it can never execute.

Soundness: the instrumentation only adds intruder knowledge (fresh markers), which cannot disable a
transition, so a "never executes" verdict carries over to the uninstrumented model. A "can execute"
verdict could in principle rely on a marker; the markers are fresh texts unrelated to the protocol.

Usage: python probes.py MODEL.hlpsl OUT.hlpsl rp9|maka_e    (prints the probe names)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

OWNERS = {
    "rp9": {"clustermember": ("cm", "CM"), "clusterhead": ("ch", "CH"), "basestation": ("bs", "BS")},
    "maka_e": {"initiator": ("i", "Ini"), "responder": ("r", "Rsp")},
}


def instrument(text: str, owners: dict[str, tuple[str, str]]) -> tuple[str, list[str]]:
    names: list[str] = []
    out: list[str] = []
    role = None
    current = ""
    for line in text.split("\n"):
        m = re.match(r"\s*role (\w+)\(", line)
        if m:
            role = m.group(1)
        t = re.match(r"\s*(\d+)\. State=", line)
        if t and role in owners:
            current = f"{owners[role][0]}{t.group(1)}"
        a = re.search(r"State':=\s*\d+", line)
        if a and role in owners and not line.lstrip().startswith("%%"):
            names.append(current)
            line = (line[:a.end()] + f" /\\ Probe_{current}':=new() /\\ SND(Probe_{current}')"
                    f" /\\ secret(Probe_{current}',probe_{current},{{{owners[role][1]}}})" + line[a.end():])
        out.append(line)
    s = "\n".join(out)
    s = re.sub(r"(        local\n                State:nat,)",
               r"\1\n                " + ",".join(f"Probe_{n}" for n in names) + ":text,", s)
    plist = ",".join(f"probe_{n}" for n in names)
    s = s.replace("sec3:protocol_id", f"sec3,{plist}:protocol_id").replace("k_ri:protocol_id", f"k_ri,{plist}:protocol_id")
    s = s.replace("\ngoal\n", "\ngoal\n" + "".join(f"        secrecy_of probe_{n}\n" for n in names), 1)
    return "%% PER-TRANSITION EXECUTABILITY PROBE (instrumentation only, generated by probes.py)\n" + s, names


def main(argv: list[str]) -> int:
    src, dst, kind = argv
    text, names = instrument(Path(src).read_text(encoding="utf-8"), OWNERS[kind])
    Path(dst).write_text(text, encoding="utf-8")
    sys.stdout.write(" ".join(names) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
