/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit */
        get: operations["audit_api_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reset-demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Demo */
        post: operations["reset_demo_api_admin_reset_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        /** Add User */
        post: operations["add_user_api_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch User */
        patch: operations["patch_user_api_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reference
         * @description RP9 table reproductions, formal results, parameter levels, latest comparison, limitations.
         */
        get: operations["get_reference_api_evaluation_reference_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_evaluation_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_evaluation_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Events */
        get: operations["export_events_api_events_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_lab_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Networks */
        get: operations["list_networks_api_networks_get"];
        put?: never;
        /** Create Network */
        post: operations["create_network_api_networks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networks/{network_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Network */
        get: operations["get_network_api_networks__network_id__get"];
        put?: never;
        post?: never;
        /** Delete Network */
        delete: operations["delete_network_api_networks__network_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networks/{network_id}/devices/{ident}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device */
        get: operations["get_device_api_networks__network_id__devices__ident__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networks/{network_id}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Frames */
        get: operations["list_frames_api_networks__network_id__frames_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networks/{network_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Job */
        post: operations["submit_job_api_networks__network_id__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networks/{network_id}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Readings
         * @description FR-07: decrypted readings at the BS -- Operator and Admin only (V-WEB-08).
         */
        get: operations["list_readings_api_networks__network_id__readings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networks/{network_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description SSE: frame, security_event, device_status, job_progress. Resumes after Last-Event-ID.
         *     `once=true` returns the buffered events and closes (used by tests and polling clients).
         */
        get: operations["stream_api_networks__network_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditOut */
        AuditOut: {
            /** Action */
            action: string;
            /** Id */
            id: number;
            /** Outcome */
            outcome: string;
            /** Target */
            target: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Username */
            username: string;
        };
        /** CheckOut */
        CheckOut: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** CustomTopology */
        CustomTopology: {
            /** Chs */
            chs: number;
            /** Cms Per Ch */
            cms_per_ch: number;
        };
        /** DeviceDetail */
        DeviceDetail: {
            device: components["schemas"]["DeviceOut"];
            /** Sessions */
            sessions: components["schemas"]["SessionOut"][];
            /** Status History */
            status_history: {
                [key: string]: unknown;
            }[];
        };
        /** DeviceOut */
        DeviceOut: {
            /** Cluster */
            cluster: string | null;
            /** Epoch */
            epoch: number;
            /** Ident */
            ident: string;
            /** Pu Fingerprint */
            pu_fingerprint: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** EventOut */
        EventOut: {
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Device */
            device: string;
            /** Frame Id */
            frame_id: number | null;
            /** Id */
            id: number;
            /** Network Id */
            network_id: number | null;
            /** Peer */
            peer: string | null;
            /** Run Tag */
            run_tag?: string | null;
            /** Session Sid */
            session_sid: string | null;
            /** Severity */
            severity: string;
            /** Step */
            step: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Type */
            type: string;
        };
        /** FrameOut */
        FrameOut: {
            /** Bytes Len */
            bytes_len: number;
            /** Checks */
            checks: components["schemas"]["CheckOut"][];
            /** Dst */
            dst: string;
            /** Fate */
            fate: string;
            /** Frame Id */
            frame_id: number;
            /** Id */
            id: number;
            /** Job Id */
            job_id: number | null;
            /** Label */
            label: string;
            /** Paper Bits */
            paper_bits: number;
            /** Payload Hex */
            payload_hex: string | null;
            /** Reason */
            reason: string | null;
            /** Run Tag */
            run_tag?: string | null;
            /** Sent Step */
            sent_step: number;
            /** Src */
            src: string;
            /** Step */
            step: number;
            /** To */
            to: string | null;
            /** Verdict */
            verdict: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobAccepted */
        JobAccepted: {
            /** Created */
            created: boolean;
            /** Job Id */
            job_id: number;
        };
        /** JobCreate */
        JobCreate: {
            /**
             * Args
             * @default {}
             */
            args: {
                [key: string]: unknown;
            };
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Type
             * @enum {string}
             */
            type: "onboard" | "step" | "send_readings" | "start_periodic" | "stop_periodic" | "rekey" | "revoke" | "reprovision" | "designate" | "lab_scenario" | "evaluation" | "reset_network";
        };
        /** JobOut */
        JobOut: {
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Network Id */
            network_id: number | null;
            /** Phase */
            phase: string;
            /** Progress */
            progress: number;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** State */
            state: string;
            /** Type */
            type: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** NetworkCreate */
        NetworkCreate: {
            custom?: components["schemas"]["CustomTopology"] | null;
            /**
             * Forward Ciphertexts
             * @default false
             */
            forward_ciphertexts: boolean;
            /**
             * Kind
             * @default product
             * @enum {string}
             */
            kind: "product" | "lab";
            /**
             * Mode
             * @default enhanced
             * @enum {string}
             */
            mode: "enhanced" | "original";
            /** Name */
            name: string;
            /**
             * Params
             * @default demo
             * @enum {string}
             */
            params: "toy" | "demo" | "secure";
            /**
             * Secure Pseudo Ids
             * @default true
             */
            secure_pseudo_ids: boolean;
            /** Seed */
            seed?: number | null;
            /**
             * Template
             * @default paper
             */
            template: ("paper" | "small" | "net") | null;
        };
        /** NetworkDelete */
        NetworkDelete: {
            /** Confirm Name */
            confirm_name: string;
        };
        /** NetworkDetail */
        NetworkDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Count */
            device_count: number;
            /** Devices */
            devices: components["schemas"]["DeviceOut"][];
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Mode */
            mode: string;
            /** Name */
            name: string;
            /**
             * Options
             * @default {}
             */
            options: {
                [key: string]: unknown;
            };
            /** Params */
            params: string;
            /** Security Level */
            security_level: string;
            /** Seed */
            seed: number | null;
            /** Status */
            status: string;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Step */
            step: number;
            /** Template */
            template: string;
            /** Tunables */
            tunables: {
                [key: string]: number;
            };
        };
        /** NetworkOut */
        NetworkOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Count */
            device_count: number;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Mode */
            mode: string;
            /** Name */
            name: string;
            /**
             * Options
             * @default {}
             */
            options: {
                [key: string]: unknown;
            };
            /** Params */
            params: string;
            /** Security Level */
            security_level: string;
            /** Seed */
            seed: number | null;
            /** Status */
            status: string;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Step */
            step: number;
            /** Template */
            template: string;
        };
        /** Page[AuditOut] */
        Page_AuditOut_: {
            /** Items */
            items: components["schemas"]["AuditOut"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /** Page[EventOut] */
        Page_EventOut_: {
            /** Items */
            items: components["schemas"]["EventOut"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /** Page[FrameOut] */
        Page_FrameOut_: {
            /** Items */
            items: components["schemas"]["FrameOut"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /** Page[ReadingOut] */
        Page_ReadingOut_: {
            /** Items */
            items: components["schemas"]["ReadingOut"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /** ReadingOut */
        ReadingOut: {
            /** Device */
            device: string;
            /** Id */
            id: number;
            /** Received Step */
            received_step: number;
            /** Seq */
            seq: number;
            /** Value */
            value: unknown;
        };
        /** ResetDemo */
        ResetDemo: {
            /** Confirm */
            confirm: string;
        };
        /** SessionInfoOut */
        SessionInfoOut: {
            /** Csrf Token */
            csrf_token: string;
            /** Role */
            role: string;
            user: components["schemas"]["UserOut"];
        };
        /** SessionOut */
        SessionOut: {
            /** A */
            a: string;
            /** B */
            b: string;
            /** Epoch */
            epoch: number;
            /** Established Step */
            established_step: number | null;
            /** Purpose */
            purpose: string;
            /** Recv */
            recv: number;
            /** Sent */
            sent: number;
            /** Sid Hex */
            sid_hex: string;
            /** State */
            state: string;
            /** Superseded By */
            superseded_by?: string | null;
        };
        /** UserCreate */
        UserCreate: {
            /** Password */
            password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "operator" | "viewer";
            /** Username */
            username: string;
        };
        /** UserOut */
        UserOut: {
            /** Disabled */
            disabled: boolean;
            /** Id */
            id: number;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "operator" | "viewer";
            /** Username */
            username: string;
        };
        /** UserPatch */
        UserPatch: {
            /** Disabled */
            disabled?: boolean | null;
            /** Password */
            password?: string | null;
            /** Role */
            role?: ("admin" | "operator" | "viewer") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit_api_admin_audit_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_demo_api_admin_reset_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetDemo"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    add_user_api_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_user_api_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfoOut"];
                };
            };
        };
    };
    get_reference_api_evaluation_reference_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_runs_api_evaluation_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_run_api_evaluation_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: {
                network?: number | null;
                severity?: string | null;
                type?: string | null;
                device?: string | null;
                since?: string | null;
                run_tag?: string | null;
                cursor?: number | null;
                limit?: number;
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EventOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_events_api_events_export_get: {
        parameters: {
            query?: {
                format?: "csv" | "json";
                network?: number | null;
                severity?: string | null;
                type?: string | null;
                device?: string | null;
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_lab_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    list_networks_api_networks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkOut"][];
                };
            };
        };
    };
    create_network_api_networks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_network_api_networks__network_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                network_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_network_api_networks__network_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                network_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_api_networks__network_id__devices__ident__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                network_id: number;
                ident: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_frames_api_networks__network_id__frames_get: {
        parameters: {
            query?: {
                label?: string | null;
                src?: string | null;
                dst?: string | null;
                verdict?: string | null;
                after_step?: number | null;
                job?: number | null;
                run_tag?: string | null;
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                network_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FrameOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_job_api_networks__network_id__jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                network_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_readings_api_networks__network_id__readings_get: {
        parameters: {
            query?: {
                device?: string | null;
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                network_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ReadingOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_networks__network_id__stream_get: {
        parameters: {
            query?: {
                last_event_id?: number | null;
                once?: boolean;
            };
            header?: never;
            path: {
                network_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
