"""initial schema (IMPLEMENTATION_PLAN.md §4.8)

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 23:45:39.601951
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_runs',
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('networks',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('params', sa.String(length=16), nullable=False),
    sa.Column('template', sa.String(length=32), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('bs_device_id', sa.String(length=20), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('devices',
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('ident', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=4), nullable=False),
    sa.Column('cluster', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('pu_fingerprint', sa.String(length=16), nullable=False),
    sa.Column('status_history', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'ident')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_network_id'), ['network_id'], unique=False)

    op.create_table('frames',
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('sent_step', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(length=20), nullable=False),
    sa.Column('dst', sa.String(length=20), nullable=False),
    sa.Column('to', sa.String(length=20), nullable=True),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('bytes_len', sa.Integer(), nullable=False),
    sa.Column('paper_bits', sa.Integer(), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('fate', sa.String(length=16), nullable=False),
    sa.Column('checks_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frames', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frames_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_frames_network_id'), ['network_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_frames_step'), ['step'], unique=False)

    op.create_table('jobs',
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('args_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'idempotency_key')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_network_id'), ['network_id'], unique=False)

    op.create_table('readings',
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=20), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('received_step', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readings_device'), ['device'], unique=False)
        batch_op.create_index(batch_op.f('ix_readings_network_id'), ['network_id'], unique=False)

    op.create_table('security_events',
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('device', sa.String(length=20), nullable=False),
    sa.Column('peer', sa.String(length=20), nullable=True),
    sa.Column('session_sid', sa.String(length=64), nullable=True),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_network_id'), ['network_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_type'), ['type'], unique=False)

    op.create_table('sessions',
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('a', sa.String(length=20), nullable=False),
    sa.Column('b', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('sid_hex', sa.String(length=64), nullable=False),
    sa.Column('established_step', sa.Integer(), nullable=True),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=False),
    sa.Column('recv', sa.Integer(), nullable=False),
    sa.Column('superseded_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_network_id'), ['network_id'], unique=False)

    op.create_table('keystore_entries',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('cls', sa.String(length=8), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'name')
    )
    with op.batch_alter_table('keystore_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keystore_entries_device_id'), ['device_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keystore_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keystore_entries_device_id'))

    op.drop_table('keystore_entries')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_network_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_type'))
        batch_op.drop_index(batch_op.f('ix_security_events_severity'))
        batch_op.drop_index(batch_op.f('ix_security_events_network_id'))

    op.drop_table('security_events')
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readings_network_id'))
        batch_op.drop_index(batch_op.f('ix_readings_device'))

    op.drop_table('readings')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_network_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('frames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frames_step'))
        batch_op.drop_index(batch_op.f('ix_frames_network_id'))
        batch_op.drop_index(batch_op.f('ix_frames_label'))

    op.drop_table('frames')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_network_id'))

    op.drop_table('devices')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))

    op.drop_table('auth_sessions')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('networks')
    op.drop_table('evaluation_runs')
    # ### end Alembic commands ###
