"""Frozen parameter sets (IA-07) and the p_field / r_group domain-naming discipline (IA-02).

No attribute named `p` exists anywhere in this module or elsewhere under src/ -- three
distinct objects across RP9 and ICMDS-P are written `p`, and conflating them is a live hazard
now that AM-09 has surfaced. See PLAN.md IA-02's domain-naming table:

    RP9 `p` (curve base field, "a large prime")        -> p_field
    ICMDS-P `p` (order of G1 and G2)                    -> r_group
    our subgroup order                                  -> r_group

`params.py` exposes only `p_field` and `r_group`; tests/test_hygiene.py forbids a bare `p`
binding anywhere under src/.
"""

from __future__ import annotations

from dataclasses import dataclass

from maka.curve import CurveParams, Point
from maka.field import Fp


@dataclass(frozen=True)
class ParamSet:
    name: str
    curve: CurveParams
    g: Point  # generator of the order-r_group subgroup
    insecure: bool  # `toy` is deliberately too small to offer any security margin


def _point(curve: CurveParams, x: int, y: int) -> Point:
    return Point(Fp(x, curve.p_field), Fp(y, curve.p_field), curve)


TOY = "toy"
DEMO = "demo"
SECURE = "secure"

# Generated by tools/gen_params.py and recorded in docs/PARAMETERS.md; not re-derived at
# import time so importing maka.params never re-runs a prime search.

# --- toy: 32-bit p_field, hand-checkable traces. INSECURE -- demonstration only. ---
_TOY_CURVE = CurveParams(p_field=2147483743, a=1, b=0, order=2147483744,
                          r_group=9586981, cofactor=224)
_TOY_G = (1070182090, 198215338)

# --- demo: 256-bit p_field, 251-bit r_group. Default parameter set. ---
_DEMO_CURVE = CurveParams(
    p_field=57896044618658097711785492504343953926634992332820282019728792003956564820459,
    a=1, b=0,
    order=57896044618658097711785492504343953926634992332820282019728792003956564820460,
    r_group=2894802230932904885589274625217197696331749616641014100986439600197828241023,
    cofactor=20,
)
_DEMO_G = (
    29319505667620971492895074292352165874684149428191334064639881252919624891171,
    43618345264868158046555741268025488731353218173564049551012759488738821419947,
)

# --- secure: 512-bit p_field, 501-bit r_group. ---
_SECURE_CURVE = CurveParams(
    p_field=6703903964971298549787012499102923063739682910296196688861780721860882015036773488400937149083451713845015929093243025426876941405973284973216824503070419,
    a=1, b=0,
    order=6703903964971298549787012499102923063739682910296196688861780721860882015036773488400937149083451713845015929093243025426876941405973284973216824503070420,
    r_group=5880617513132718026128958332546423740122528868680874288475246247246387732488397796842927323757413784074575376397581601251646439829801127169488442546553,
    cofactor=1140,
)
_SECURE_G = (
    3326394976667209791298025781150570929339983973173255598647360113068823133070141595325272987833692323186457580580456861036038137096973360377332480412627225,
    6234189450018462537287419028826629994873634029743242514082883721260258450830704656651413281585591580609523495927748197733949267332468080203438134185301917,
)

_REGISTRY: dict[str, ParamSet] = {}


def register(param_set: ParamSet) -> None:
    _REGISTRY[param_set.name] = param_set


def get(name: str) -> ParamSet:
    if name not in _REGISTRY:
        _bootstrap(name)
    return _REGISTRY[name]


def _bootstrap(name: str) -> None:
    table = {
        TOY: (_TOY_CURVE, _TOY_G, True),
        DEMO: (_DEMO_CURVE, _DEMO_G, False),
        SECURE: (_SECURE_CURVE, _SECURE_G, False),
    }
    if name not in table:
        raise KeyError(f"unknown parameter set {name!r}")
    curve, (gx, gy), insecure = table[name]
    register(ParamSet(name=name, curve=curve, g=_point(curve, gx, gy), insecure=insecure))
