"""Generates docs/FIDELITY.md from the docstring headers under src/, attacks/, security/,
formal/, eval/ that name the RP9 sections and register IDs they realise (see PLAN.md §2).

Run standalone: `python tools/build_fidelity_matrix.py`.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCAN_DIRS = ["src", "attacks", "security", "formal", "eval"]

REALISES_RE = re.compile(r"Realises:\s*(.+?)(?:\n\n|\nApplies:|\"\"\")", re.DOTALL)
APPLIES_RE = re.compile(r"Applies:\s*(.+?)(?:\n\n|\"\"\")", re.DOTALL)
DOCSTRING_RE = re.compile(r'"""(.*?)"""', re.DOTALL)
SECTION_MENTION_RE = re.compile(r"§[\d.]+")

# RP9 sections this project is required to cover (PLAN.md §2, §1.2)
REQUIRED_SECTIONS = [f"§{n}" for n in ("2.1", "2.2", "2.3", "3", "4.1", "4.2", "4.3", "4.4",
                                        "4.5", "4.6", "4.7", "5.1", "5.2", "5.3", "5.4", "5.5",
                                        "6.1.1", "6.1.2", "6.1.3", "6.1.4", "6.1.5", "6.1.6",
                                        "6.1.7", "6.2", "6.3", "7.1", "7.2", "7.3", "8")]


def scan() -> list[tuple[str, str, str]]:
    """Returns (path, realises-text, applies-text). Prefers an explicit `Realises:` header;
    falls back to the module docstring's first paragraph if it mentions an RP9 section (many
    files describe their RP9 mapping in prose rather than the strict header, e.g. protocol
    phase modules) -- both count toward the coverage figure below.
    """
    entries = []
    for d in SCAN_DIRS:
        for f in (REPO_ROOT / d).rglob("*.py"):
            if f.name.startswith("_") or f.name == "__init__.py":
                continue
            text = f.read_text(encoding="utf-8")
            m_realises = REALISES_RE.search(text)
            m_applies = APPLIES_RE.search(text)
            if m_realises:
                realises = " ".join(m_realises.group(1).split())
                applies = " ".join(m_applies.group(1).split()) if m_applies else ""
                entries.append((str(f.relative_to(REPO_ROOT)), realises, applies))
                continue
            m_doc = DOCSTRING_RE.search(text)
            if m_doc and SECTION_MENTION_RE.search(m_doc.group(1)):
                first_para = m_doc.group(1).strip().split("\n\n")[0]
                entries.append((str(f.relative_to(REPO_ROOT)), " ".join(first_para.split()), ""))
    return entries


def build() -> str:
    entries = scan()
    covered_sections = set()
    for _, realises, applies in entries:
        for sec in REQUIRED_SECTIONS:
            if sec in realises or sec in applies:
                covered_sections.add(sec)

    intro = ("Auto-generated by `tools/build_fidelity_matrix.py` from `Realises:`/`Applies:` "
             "docstring headers under src/, attacks/, security/, formal/, eval/ (PLAN.md §2).")
    lines = ["# FIDELITY", "", intro, ""]

    coverage_pct = 100 * len(covered_sections) / len(REQUIRED_SECTIONS)
    lines.append(f"**Coverage: {len(covered_sections)}/{len(REQUIRED_SECTIONS)} RP9 §2-§8 "
                 f"subsections referenced ({coverage_pct:.0f}%)**")
    lines.append("")
    missing = [s for s in REQUIRED_SECTIONS if s not in covered_sections]
    if missing:
        lines.append(f"Missing: {', '.join(missing)}")
        lines.append("")

    lines.append("| File | Realises | Applies |")
    lines.append("|---|---|---|")
    for path, realises, applies in sorted(entries):
        lines.append(f"| `{path}` | {realises} | {applies} |")

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    out = REPO_ROOT / "docs" / "FIDELITY.md"
    out.write_text(build(), encoding="utf-8")
    print(f"wrote {out}")
