"""Writes docs/API.md: hand-written prose plus tables generated from the FastAPI app (M8-T3).

The endpoint table (method, path, minimum role, summary) comes from the app's routes, with the role
read from each route's dependency tree, so it cannot drift from the code. Job types come from the
registered handlers. Run `make openapi` first; `tests/test_docs.py` checks the file is current.
"""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))
OUT = REPO_ROOT / "docs" / "API.md"

PROSE = """\
# Console API

The console's HTTP API, used by the web UI. It is served under `/api` by `python -m maka_server serve`.
The machine-readable description is [`docs/openapi.json`](openapi.json), regenerated by `make openapi`;
the live server serves Swagger UI at `/api/docs`. The endpoint and job tables below are generated from
the code by `tools/gen_api_doc.py`. Do not edit them by hand.

## Conventions

- **Authentication.** `POST /api/auth/login` sets an `HttpOnly`, `SameSite=Strict` session cookie
  (`Secure` unless bound to loopback) and returns a `csrf_token`. Every state-changing request (`POST`,
  `PATCH`, `DELETE`) must send it as `X-CSRF-Token`. Sessions expire after `MAKA_SESSION_IDLE_HOURS`
  of inactivity. Repeated failures lock the account for `MAKA_LOGIN_LOCK_S`.
- **Roles.** Viewer < Operator < Admin. A role can do everything a lower role can. "signed in" means any
  role. Viewers never receive decrypted readings.
- **Errors** are `application/problem+json`: `{type, title, status, detail, code}`, where `code` is a
  stable identifier (`VALIDATION_FAILED`, `MODE_NOT_ALLOWED`, `NETWORK_BUSY`, `IDEMPOTENCY_CONFLICT`,
  `NAME_TAKEN`, `CONFIRMATION_MISMATCH`, `FORBIDDEN`, `NOT_FOUND`, ...).
- **Jobs.** All protocol work is asynchronous. `POST /api/networks/{id}/jobs` with
  `{type, args, idempotency_key}` returns `202 {job_id, created}`. Repeating a key with the same body
  returns the same job; the same key with a different body is `409 IDEMPOTENCY_CONFLICT`. Jobs on one
  network run one at a time. Poll `GET /api/jobs/{id}` or follow `job_progress` on the stream. States:
  `queued → running → succeeded | failed | cancelled`, plus `aborted` for a job found running at
  startup (the network is then rebuilt from the database, §4.8).
- **Mode rules.** Product networks run MAKA-E only. `lab_scenario` and `evaluation` jobs require a lab
  network (`422 MODE_NOT_ALLOWED`).
- **Streaming.** `GET /api/networks/{id}/stream` is Server-Sent Events (`frame`, `security_event`,
  `device_status`, `job_progress`). Reconnect with `Last-Event-ID` to receive buffered events without
  duplicates.
- **Pagination.** List endpoints return `{items, next_cursor}`. Pass `cursor=<next_cursor>` for the next
  page.
- **Secrets.** No endpoint returns key material or session-key fingerprints (§4.4). Frames carry
  ciphertext metadata; Lab results name the secrets an attack obtained, never their values.
"""


def _role(route: Any) -> str:
    from maka_server import deps

    names = {deps.viewer: "viewer", deps.operator: "operator", deps.admin: "admin",
             deps.current_user: "signed in"}
    stack = list(route.dependant.dependencies)
    found = "public"
    order = ["public", "signed in", "viewer", "operator", "admin"]
    while stack:
        dep = stack.pop()
        role = names.get(dep.call)
        if role is not None and order.index(role) > order.index(found):
            found = role
        stack.extend(dep.dependencies)
    return found


def render() -> str:
    from fastapi.routing import APIRoute

    from maka_server.jobs import HANDLERS
    from maka_server.main import create_app
    from maka_server.services.jobrules import LAB_ONLY
    from maka_server.settings import Settings

    with tempfile.TemporaryDirectory() as tmp:
        app = create_app(Settings(env="test", db_url=f"sqlite:///{tmp}/api.db"))
    def walk(routes: list[Any], prefix: str = "") -> Any:
        for r in routes:
            if isinstance(r, APIRoute):
                yield prefix + r.path, r
            elif hasattr(r, "original_router"):  # FastAPI >= 0.140 wraps included routers
                yield from walk(r.original_router.routes, prefix + getattr(r.include_context, "prefix", ""))

    rows = []
    for path, r in walk(app.routes):
        if path.startswith("/api"):
            for method in sorted(r.methods - {"HEAD", "OPTIONS"}):
                doc = (r.description or "").strip().splitlines()
                rows.append((path, method, _role(r), r.summary or r.name.replace("_", " ").capitalize(),
                             doc[0] if doc else ""))
    lines = [PROSE, "## Endpoints", "", "| Method | Path | Minimum role | Summary |", "|---|---|---|---|"]
    for path, method, role, summary, first in sorted(rows):
        text = f"{summary}. {first}" if first else summary
        lines.append(f"| `{method}` | `{path}` | {role} | {text} |")
    lines += ["", "## Job types", "",
              "| Type | Networks | Handler |", "|---|---|---|"]
    for name, fn in sorted(HANDLERS.items()):
        where = "lab only" if name in LAB_ONLY else ("none (global)" if name == "reset_demo" else "any")
        lines.append(f"| `{name}` | {where} | `{fn.__module__}.{fn.__name__}` |")
    return "\n".join(lines) + "\n"


def main() -> int:
    OUT.write_text(render(), encoding="utf-8")
    sys.stdout.write(f"wrote {OUT}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
